# Generated by Django 3.1 on 2020-09-19 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note_logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('notepad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note_logs.notepad')),
            ],
            options={
                'verbose_name_plural': 'notes',
            },
        ),
    ]
